### ISSUE TITLE
Alguns objetos não são adicionados corretamente à WatchWindow

### ISSUE THREAD

**Issue by DumkeMKS** [leandrobpedro/watch-window-rt#2]
Objetos da estrutura do projeto, como: Dados, Driver1, Driver2, Historico e etc., apresentam seus valores e seus nomes ao adicioná-los na WatchWindows, porém qualquer outro objeto dentro das pastas subsequentes não apresentam seu nome nem valor.

Versão do Elipse E3: 6.5.150

Versão do Windows: 
Edição	Windows 10 Home Single Language
Versão	22H2
Instalado em	‎27/‎01/‎2023
Compilação do SO	19045.2846
Experiência	Windows Feature Experience Pack 120.2212.4190.0

![WatchWindow](https://user-images.githubusercontent.com/131976344/234867449-f5ec664f-42d6-49ff-91ae-27a2b048d55c.png)
![WatchWindow1](https://user-images.githubusercontent.com/131976344/234874234-2ba2729f-e6a1-42be-8f0c-ddb5662315b5.png)

**Comment by leandrobpedro** [comment]
Olá,

De fato este ocorre nesta versão pois o Elipse não reconhece contrabarra no caminho do objeto, por exemplo:
```vbs
Set obj = Application.GetObject("Caminho\Do\Objeto")
```

Isto foi corrigido no release 1.0.3 para algo como:
```vbs
Set obj = Application.GetObject("[Caminho].[Do].[Objeto]")
```

Por isso funciona em objetos do primeiro nível somente.

Agradeço os detalhes enviados, @DumkeMKS

**Comment by DumkeMKS** [comment]
Entendido, disponha.
